#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

--when.repositories = ["~/relex"]

[user]
email = "dean.todevski@relexsolutions.com"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | master@origin"
